services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - 'mongo_data:/var/lib/mysql'

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    ports:
      - '${DOZZLE_PORT}:8080'
    volumes:
      - '//var/run/docker.sock:/var/run/docker.sock'  #  windows
      # - '/var/run/docker.sock:/var/run/docker.sock' #  linux

  grafana:
    image: grafana/grafana
    restart: always
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel, grafana-clickhouse-datasource, grafana-simple-json-datasource"
    ports:
      - '${GRAFANA_PORT}:3000'
    links:
      - "clickhouse:clickhouse"
    volumes:
      - "${DATA_PATH}/grafana/storage:/var/lib/grafana"
    networks:
      - logs

  clickhouse:
    image: bitnami/clickhouse:latest
    restart: always
    ports:
      - '${CLICKHOUSE_HTTP_PORT}:8123'
      - '${CLICKHOUSE_TCP_PORT}:9000'
      - '${CLICKHOUSE_MYSQL_PORT}:9004'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - "clickhouse-data:/bitnami/clickhouse"
      - "${DATA_PATH}/clickhouse/config:/bitnami/clickhouse/etc/conf.d"
    networks:
      - logs

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    privileged: true
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_DOMAIN_NAME}'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['initial_root_password'] = '${GIT_ROOT_PASSWORD}'
    volumes:
      - "git-config:/etc/gitlab"
      - "git-data:/var/opt/gitlab"
      - "${DATA_PATH}/gitlab/logs:/var/log/gitlab"
    ports:
      - ${GIT_SSH_PORT}:22
      - ${GIT_HTTP_PORT}:80
      - ${GIT_HTTPS_PORT}:443
    shm_size: 256m
    networks:
      gitlab:
        ipv4_address: 192.168.201.2

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - ".local/runner/config:/etc/gitlab-runner"
      - ".local/runner/home_config:/home/gitlab-runner"
      - '//var/run/docker.sock:/var/run/docker.sock'  #  windows
      # - '/var/run/docker.sock:/var/run/docker.sock' #  linux
    links:
      - gitlab:gitlab
    environment:
      - CI_SERVER_URL="http://gitlab"
      - RUNNER_NAME=gitlab-runner
    networks:
      gitlab:
        ipv4_address: 192.168.201.3

volumes:
  mysql_data:
  mongo_data:
  clickhouse-data:
  git-config:
  git-data:

networks:
  logs:
    driver: bridge
  gitlab:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.201.0/24
          gateway: 192.168.201.1
