concurrent = 2
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlab-runner"
  url = "http://192.168.201.2"
  id = 1
  token = "glrt-DJUSx_-u91oAJEogkeaY"
  token_obtained_at = 2024-04-09T05:50:20Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  clone_url = "http://192.168.201.2/"
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    network_mode = "volumes_gitlab"
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "shell-runner"
  url = "http://192.168.201.2"
  id = 2
  token = "glrt-aJKfgrzsjScyfc-u88Py"
  token_obtained_at = 2024-04-16T07:39:23Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  clone_url = "http://192.168.201.2/"

[[runners]]
  name = "personal test"
  url = "http://47.107.251.91/"
  id = 18
  token = "UyyzJMMxxixLJCFQMdeX"
  token_obtained_at = 2024-04-19T08:40:49Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "debian:12-slim"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
